apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  outbound:
    serviceReferences:
    - name: choreo:///teslachallenge/backend/umprpe/803f0/v1/ORGANIZATION
      connectionConfig: 01ef0712-fd2a-17a8-b2b0-13a77ea6b1fb
      env:
      - from: ServiceURL
        to: SERVICE_URL
      - from: ConsumerKey
        to: CONSUMER_KEY
      - from: ConsumerSecret
        to: CONSUMER_SECRET
      - from: TokenURL
        to: TOKEN_URL

